/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   wrapper__init
                     (Wrapper         *message)
{
  static const Wrapper init_value = WRAPPER__INIT;
  *message = init_value;
}
size_t wrapper__get_packed_size
                     (const Wrapper *message)
{
  assert(message->base.descriptor == &wrapper__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wrapper__pack
                     (const Wrapper *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wrapper__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wrapper__pack_to_buffer
                     (const Wrapper *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wrapper__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wrapper *
       wrapper__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wrapper *)
     protobuf_c_message_unpack (&wrapper__descriptor,
                                allocator, len, data);
}
void   wrapper__free_unpacked
                     (Wrapper *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wrapper__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   packet__init
                     (Packet         *message)
{
  static const Packet init_value = PACKET__INIT;
  *message = init_value;
}
size_t packet__get_packed_size
                     (const Packet *message)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet__pack
                     (const Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet__pack_to_buffer
                     (const Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Packet *
       packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Packet *)
     protobuf_c_message_unpack (&packet__descriptor,
                                allocator, len, data);
}
void   packet__free_unpacked
                     (Packet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wrapper__field_descriptors[2] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wrapper, tag),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packets",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Wrapper, n_packets),
    offsetof(Wrapper, packets),
    &packet__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wrapper__field_indices_by_name[] = {
  1,   /* field[1] = packets */
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange wrapper__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wrapper__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Wrapper",
  "Wrapper",
  "Wrapper",
  "",
  sizeof(Wrapper),
  2,
  wrapper__field_descriptors,
  wrapper__field_indices_by_name,
  1,  wrapper__number_ranges,
  (ProtobufCMessageInit) wrapper__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor packet__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Packet, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Packet, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Packet",
  "Packet",
  "Packet",
  "",
  sizeof(Packet),
  2,
  packet__field_descriptors,
  packet__field_indices_by_name,
  1,  packet__number_ranges,
  (ProtobufCMessageInit) packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
